name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This is a stale issue, if not done within 15 days will be closed. Thank you!'
        stale-pr-message: 'This is a stale pull request, if not done within 15 days will be closed. Thank you!'
        stale-issue-label: 'no-activity'
        stale-pr-label: 'no-activity'
